name: recipe_finder
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.2.1
  get_it: ^7.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  logger: ^1.1.0
  provider: ^6.0.4
  retrofit: ^3.3.1

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.3
  retrofit_generator: '>=4.0.0 <5.0.0'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: Hammersmith One
      fonts:
        - asset: assets/fonts/HammersmithOne-Regular.ttf

    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppins-ExtraBold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
